[theme]
base = "dark"
primaryColor = "#88A9FF"
backgroundColor = "#07111F"
secondaryBackgroundColor = "#0C1728"
textColor = "#F6F8FC"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "minimal"
